=== fwip/exp_schema/schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Experiment",
  "description": "A description of an experiment",
  "type": "object",

  "additionalProperties": false,

  "properties": {

    "schema_version": {
      "description": "The version of schema that this experiment conforms to",
      "type": "string"
    },

    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },

    "factors": {
      "description": "A list of factors that matter in this experimental design",
      "type": "array",
      "items": {
        "type": "string",
        "uniqueItems": true
      }
    },

    "display": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "views": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "x": {
          "type": "array",
          "items": {
            "type": "string",
            "uniqueItems": true
          }
        },
        "y": {
          "type": "array",
          "items": {
            "type": "string",
            "uniqueItems": true
          }
        }
      }
    },

    "conditions": {
      "description": "A list of conditions (combinations of factors)",
      "type": "array",
      "items": {
        "$ref": "#/definitions/condition"
      }
    }
  },

  "definitions": {
    "condition": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "aggregation_ids": {
            "type": "array",
            "items": {
              "type": "number",
              "uniqueItems": true
            }
          },
          "factors": {
            "type": "object",
            "patternProperties": {
              "/^[-a-z]+$/": {
                "type": "string"
              }
            }
          }
        },
        "required": ["factors"]
    }
  },

  "required": ["schema_version", "name", "factors", "conditions"]
}

=== fwip/exp_schema/rcc-kidney-dnase.schema.json
{
  "schema_version": "0.2",
  "name": "RCC Kidney DNase",
  "description": "Mapping the kidney DNase landscape",
  "factors": [
    "donor",
    "tissue_type"
  ],
  "display": {
    "views": [
      "dhs",
      "signal",
      "normalized",
      "cut-counts",
      "footprints"
    ],
    "x": ["donor"],
    "y": ["tissue_type"]
  },
  "conditions": [{
      "aggregation_ids": [3844, 3864],
      "factors": {
        "donor": "NA",
        "tissue_type": "786_O"
      }
    }, {
      "aggregation_ids": [3885, 3871],
      "factors": {
        "donor": "NA",
        "tissue_type": "ACHN"
      }
    }, {
      "aggregation_ids": [3851],
      "factors": {
        "donor": "HIM12",
        "tissue_type": "glomeruli"
      }
    }, {
      "aggregation_ids": [6995, 6996],
      "factors": {
        "donor": "HIM18",
        "tissue_type": "glomeruli"
      }
    }, {
      "aggregation_ids": [3852],
      "factors": {
        "donor": "HIM22",
        "tissue_type": "glomeruli"
      }
    }, {
      "aggregation_ids": [6999, 7000],
      "factors": {
        "donor": "HIM23",
        "tissue_type": "glomeruli"
      }
    }, {
      "aggregation_ids": [7003],
      "factors": {
        "donor": "HIM26",
        "tissue_type": "glomeruli"
      }
    }, {
      "aggregation_ids": [7006, 7007],
      "factors": {
        "donor": "NA",
        "tissue_type": "HK_2"
      }
    }, {
      "aggregation_ids": [3898, 3899],
      "factors": {
        "donor": "HIM13",
        "tissue_type": "kidney_tubular"
      }
    }, {
      "aggregation_ids": [6997, 3845],
      "factors": {
        "donor": "HIM15",
        "tissue_type": "kidney_tubular"
      }
    }, {
      "aggregation_ids": [7004, 7005],
      "factors": {
        "donor": "HIM23",
        "tissue_type": "kidney_tubular"
      }
    }, {
      "aggregation_ids": [6994, 6992],
      "factors": {
        "donor": "NA",
        "tissue_type": "podocytes"
      }
    }, {
      "aggregation_ids": [6993, 3819],
      "factors": {
        "donor": "HIM13",
        "tissue_type": "renal_cell_carcinoma"
      }
    }, {
      "aggregation_ids": [3863, 6998],
      "factors": {
        "donor": "HIM15",
        "tissue_type": "renal_cell_carcinoma"
      }
    }, {
      "aggregation_ids": [7001, 7002],
      "factors": {
        "donor": "HIM23",
        "tissue_type": "renal_cell_carcinoma"
      }
    }, {
      "aggregation_ids": [9809, 9810],
      "factors": {
        "donor": "NA",
        "tissue_type": "vascular_endothelium"
      }
    }

  ]
}
